import test from "node:test";
import assert from "node:assert/strict";
import { createServer } from "node:http";
import { PlaywrightBrowserAdapter } from "../dist/playwright.js";
import type { BrowserInspection, BrowserDiagnostics, BrowserArtifact } from "../src/commands.js";
const pause = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
test("semantic/frame targets, structured inspection, pointer actions, safe dialogs, diagnostics and trace artifacts", { timeout: 90000 }, async () => {
  const server = createServer((request, response) => {
    response.setHeader("content-type", "text/html");
    if (request.url === "/frame") { response.end('<label>Frame field<input></label><iframe id="nested" src="/inner"></iframe>'); return; }
    if (request.url === "/inner") { response.end('<label>Nested field<input></label>'); return; }
    response.end(`<!doctype html><title>Interaction fixture</title><label>Name<input id="name" data-testid="name"></label><label>Password<input type="password" value="do-not-inspect"></label><button id="apply" onclick="document.querySelector('#result').textContent=document.querySelector('#name').value">Apply</button><p id="result"></p><button onclick="window.dialogResult=prompt('Private prompt')">Prompt</button><div id="source" draggable="true" ondragstart="event.dataTransfer.setData('text/plain','moved')" style="width:100px;height:50px;background:red">Drag me</div><div id="destination" ondragover="event.preventDefault()" ondrop="event.preventDefault();this.textContent=event.dataTransfer.getData('text/plain')" style="width:100px;height:50px;background:blue;margin-left:150px">Drop here</div><iframe id="frame" src="/frame"></iframe>`);
  });
  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const address = server.address(); assert.ok(address && typeof address === "object");
  const url = `http://127.0.0.1:${address.port}`;
  const adapter = new PlaywrightBrowserAdapter({ executablePath: process.env.STATION_TEST_CHROMIUM });
  const session = await adapter.open(); let limited: Awaited<ReturnType<PlaywrightBrowserAdapter["open"]>> | undefined;
  try {
    assert.equal(adapter.capabilities.inspection, true); assert.equal(adapter.capabilities.tracing, true);
    await session.navigate(url);
    await session.execute!({ op: "fill", target: { by: "label", value: "Name", exact: true }, value: "semantic target" });
    await session.execute!({ op: "click", target: { by: "role", role: "button", name: "Apply", exact: true } });
    assert.equal(await session.evaluate("document.querySelector('#result').textContent"), "semantic target");
    await session.execute!({ op: "focus", target: { by: "testId", value: "name" } });
    await session.execute!({ op: "press", target: { by: "testId", value: "name" }, key: "End" });
    await session.type("x"); await session.execute!({ op: "press", target: { by: "testId", value: "name" }, key: "Backspace" });
    await session.execute!({ op: "click", target: { by: "text", value: "Apply", exact: true } });
    await session.execute!({ op: "fill", target: { by: "label", value: "Nested field", frame: ["#frame", "#nested"] }, value: "inside nested frame" });
    const framed = await session.execute!({ op: "inspect", target: { by: "label", value: "Nested field", frame: ["#frame", "#nested"] } }) as BrowserInspection;
    assert.equal(framed.elements[0].value, "inside nested frame"); assert.equal(framed.coordinateSpace, "frame-viewport");
    const cut = await session.execute!({ op: "inspect", maxElements: 2, maxTextLength: 8 }) as BrowserInspection;
    assert.equal(cut.elements.length, 2); assert.equal(cut.truncated, true); assert.ok(cut.elements.every((element) => element.text.length <= 8));
    const password = await session.execute!({ op: "inspect", target: { by: "label", value: "Password" } }) as BrowserInspection;
    assert.equal(password.elements[0].value, undefined);
    const aria = await session.execute!({ op: "accessibility", depth: 5, boxes: true }) as { format: string; snapshot: string };
    assert.equal(aria.format, "aria-yaml"); assert.match(aria.snapshot, /button "Apply"/);
    const button = await session.execute!({ op: "inspect", target: { by: "role", role: "button", name: "Apply" } }) as BrowserInspection;
    const box = button.elements[0].box!;
    await session.execute!({ op: "fill", target: { by: "testId", value: "name" }, value: "coordinate click" });
    await session.execute!({ op: "mouseMove", x: box.x + box.width / 2, y: box.y + box.height / 2 });
    await session.execute!({ op: "mouseClick", x: box.x + box.width / 2, y: box.y + box.height / 2 });
    assert.equal(await session.evaluate("document.querySelector('#result').textContent"), "coordinate click");
    await session.execute!({ op: "drag", source: { by: "selector", value: "#source" }, destination: { by: "selector", value: "#destination" } });
    assert.equal(await session.evaluate("document.querySelector('#destination').textContent"), "moved");
    await session.evaluate("window.pointerMoved=false;document.addEventListener('pointermove',e=>{if(e.buttons===1)window.pointerMoved=true})");
    await session.execute!({ op: "dragCoordinates", from: { x: 500, y: 10 }, to: { x: 550, y: 50 }, steps: 5 });
    assert.equal(await session.evaluate("window.pointerMoved"), true);
    await session.execute!({ op: "dialog", action: "accept", promptText: "accepted once" });
    await session.execute!({ op: "click", target: { by: "role", role: "button", name: "Prompt" } });
    assert.equal(await session.evaluate("window.dialogResult"), "accepted once");
    await session.execute!({ op: "click", target: { by: "role", role: "button", name: "Prompt" } });
    assert.equal(await session.evaluate("window.dialogResult"), null);
    await session.execute!({ op: "dialog", action: "accept", promptText: "expired", expiresInMs: 1 }); await pause(20);
    await session.execute!({ op: "click", target: { by: "role", role: "button", name: "Prompt" } });
    assert.equal(await session.evaluate("window.dialogResult"), null);
    await session.evaluate("console.log('private-console-secret'); fetch('/resource?token=private-query#private-fragment')");
    const defaults = await session.execute!({ op: "diagnostics" }) as BrowserDiagnostics;
    assert.ok(defaults.events.some((event) => event.kind === "console")); assert.ok(defaults.events.filter((event) => event.kind === "console").every((event) => !event.message));
    assert.ok(!JSON.stringify(defaults).includes("private-query")); assert.ok(!JSON.stringify(defaults).includes("private-console-secret"));
    await session.execute!({ op: "diagnostics", consoleText: true, clear: true });
    await session.evaluate("console.log('https://user:password@example.com/path?token=private-query#fragment')");
    const verbose = await session.execute!({ op: "diagnostics" }) as BrowserDiagnostics;
    assert.ok(verbose.events.some((event) => event.message === "https://example.com/path"));
    await session.evaluate("for(let i=0;i<250;i++)console.log('bounded '+i+' '+ 'x'.repeat(4096))");
    const bounded = await session.execute!({ op: "diagnostics" }) as BrowserDiagnostics;
    assert.ok(bounded.events.length <= 200); assert.ok(bounded.events.every((event) => (event.message?.length ?? 0) <= 2048));
    const redacted = await session.execute!({ op: "diagnostics", consoleText: false }) as BrowserDiagnostics;
    assert.ok(redacted.events.filter((event) => event.kind === "console").every((event) => !event.message));
    await session.execute!({ op: "traceStart" });
    await assert.rejects(session.execute!({ op: "traceStart" }), { code: "busy" });
    await session.execute!({ op: "click", target: { by: "role", role: "button", name: "Apply" } });
    const trace = await session.execute!({ op: "traceStop" }) as BrowserArtifact;
    assert.equal(trace.mimeType, "application/zip"); assert.ok(trace.bytes > 0 && trace.bytes <= 4 * 1024 * 1024);
    const zip = await session.execute!({ op: "downloadRead", artifactId: trace.id }) as { base64: string };
    assert.equal(Buffer.from(zip.base64, "base64").subarray(0, 4).toString("hex"), "504b0304");
    await session.execute!({ op: "downloadDelete", artifactId: trace.id });
    await assert.rejects(session.execute!({ op: "downloadRead", artifactId: trace.id }), { code: "not_found" });
    limited = await new PlaywrightBrowserAdapter({ executablePath: process.env.STATION_TEST_CHROMIUM, maxArtifactBytes: 1 }).open();
    await limited.navigate(url); await limited.execute!({ op: "traceStart" });
    const deadline = Date.now() + 5000;
    while ((await limited.execute!({ op: "diagnostics" }) as BrowserDiagnostics).trace.status === "recording" && Date.now() < deadline) await pause(50);
    assert.equal((await limited.execute!({ op: "diagnostics" }) as BrowserDiagnostics).trace.status, "limit");
    await assert.rejects(limited.execute!({ op: "traceStop" }), { code: "output_limit" });
  } finally { await Promise.allSettled([session.close(), limited?.close()]); await new Promise<void>((resolve) => server.close(() => resolve())); }
});
