"use client";
import { useEffect, useState } from "react";
import { RegistryLink as Link, useRegistry } from "./registry-context";
import { useRouter } from "next/navigation";
import { environmentBindings } from "./registry-api.mjs";

interface Generation { id:string; image:{digest:string;manifest:{name:string;version:string;exports:{name:string;kind:string}[]}}; aliases:Record<string,string>;stationId?:string;createdAt:string;bindings?:Record<string,{fromEnv:string}|{value:string}> }
interface Deployment { id:string;name:string;revision:number;activeGeneration?:string;generations:Generation[];history:{revision:number;action:string;generation?:string;at:string}[] }
const enc=encodeURIComponent;
const base=(id:string)=>`/registry/deployments/${enc(id)}`;
const message=(error:unknown)=>error instanceof Error?error.message:String(error);
export default function DeploymentScreen({path}:{path:string[]}) {
  const {request}=useRegistry();
  const [records,setRecords]=useState<Deployment[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [revision,setRevision]=useState(0);
  const id=path[0]!=="stage"?path[0]:undefined;const operation=path[1];const selected=records.find(item=>item.id===id);const route=path.join("/");
  useEffect(()=>{let live=true;setLoading(true);setError(null);request('/deployments').then((items:Deployment[])=>{if(live)setRecords(items);}).catch((e:unknown)=>{if(live)setError(message(e));}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[route,revision]);
  return <><div className="registry-heading"><h1 className="page-title">{selected?.name??(path[0]==="stage"?"Stage deployment":"Deployments")}</h1><button className="btn" disabled={loading} onClick={()=>setRevision(v=>v+1)}>Refresh</button></div><nav className="registry-tabs" aria-label="Registry"><Link href="/registry">Images</Link><Link href="/registry/deployments" aria-current="page">Deployments</Link></nav>
    {error&&<div className="execution-error" role="alert">{error}</div>}
    {loading?<p role="status">Loading deployments…</p>:error?<p className="execution-note">Deployments require configured image execution and operator admin access.</p>:path[0]==="stage"?<StageDeployment/>:!id?<><p className="execution-intro">Versioned export aliases with explicit activation and rollback.</p><Link className="btn btn-primary" href="/registry/deployments/stage">Stage deployment</Link><div className="registry-list">{records.map(item=><Link key={item.id} className="registry-row" href={base(item.id)}><strong>{item.name}</strong><span>{item.generations.length} generations</span><span>{item.activeGeneration?"Active":"Inactive"} · revision {item.revision}</span><span aria-hidden="true">→</span></Link>)}</div>{!records.length&&<p className="execution-note">No deployments staged. Choose a published image to create the first generation.</p>}</>:!selected?<p>Deployment not found in this registry.</p>:<>
      <nav className="registry-tabs" aria-label="Deployment"><Link href={base(id)} aria-current={!operation?"page":undefined}>Generations</Link><Link href={`${base(id)}/stage`} aria-current={operation==="stage"?"page":undefined}>Stage update</Link><Link href={`${base(id)}/run`} aria-current={operation==="run"?"page":undefined}>Invoke</Link><Link href={`${base(id)}/history`} aria-current={operation==="history"?"page":undefined}>History</Link><Link href={`${base(id)}/drain`} aria-current={operation==="drain"?"page":undefined}>Drain</Link></nav>
      <p className="execution-note">Revision {selected.revision} · {selected.activeGeneration?`Active generation ${selected.activeGeneration}`:"No active generation"}</p>
      {operation==="stage"?<StageDeployment key={route} deployment={selected}/>:operation==="run"?<RunDeployment key={route} deployment={selected}/>:operation==="history"?<div className="registry-list">{[...selected.history].reverse().map(event=><article className="registry-row" key={event.revision}><strong>{event.action}</strong><span>revision {event.revision}</span><span>{new Date(event.at).toLocaleString()}<br/>{event.generation}</span></article>)}</div>:operation==="drain"?<ChangeGeneration key={route} deployment={selected} action="drain" refresh={()=>setRevision(v=>v+1)}/>:operation==="generations"?(()=>{const generation=selected.generations.find(g=>g.id===path[2]);return generation?<GenerationDetails key={route} deployment={selected} generation={generation} refresh={()=>setRevision(v=>v+1)}/>:<p>Generation not found.</p>;})():operation?<p>Deployment page not found.</p>:<div className="registry-list">{[...selected.generations].reverse().map(g=><Link className="registry-row" key={g.id} href={`${base(id)}/generations/${enc(g.id)}`}><strong>{g.image.manifest.name}<br/><span className="mono">{g.image.manifest.version}</span></strong><span>{selected.activeGeneration===g.id?"Active":"Staged / retained"}</span><span className="mono">{g.id}</span><span aria-hidden="true">→</span></Link>)}</div>}
    </>}
  </>;
}
function StageDeployment({deployment}:{deployment?:Deployment}) {
  const {post,href}=useRegistry(); const [bindings,setBindings]=useState<BindingRow[]>([]);
  const router=useRouter();const [name,setName]=useState(deployment?.name??"");const [reference,setReference]=useState("");const [aliases,setAliases]=useState("");const [stationId,setStationId]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
  return <section className="card execution-card registry-panel"><h2>{deployment?"Stage a new generation":"Create a deployment"}</h2><p className="execution-note">Staging validates image compatibility without activating aliases or invoking code. Review the generation before activation.</p><form onSubmit={async event=>{event.preventDefault();setBusy(true);setError(null);try{const mapping=aliases.trim()?JSON.parse(aliases):undefined;if(mapping&&(!Object.keys(mapping).length||Array.isArray(mapping)||Object.values(mapping).some(v=>typeof v!=="string")))throw new Error('Aliases must be a JSON object mapping each alias to an export name.');const environment=environmentBindings(bindings);const result:Deployment=await post('/deployments',{name,reference,...(mapping?{aliases:mapping}:{}),...(stationId?{stationId}:{}),...(bindings.length?{bindings:environment}:{})});const generation=result.generations.at(-1);router.push(href(generation?`${base(result.id)}/generations/${enc(generation.id)}`:base(result.id)));}catch(e){setError(message(e));}finally{setBusy(false);}}}>
    <label className="execution-field"><span>Deployment name</span><input className="input-text" required value={name} readOnly={Boolean(deployment)} onChange={e=>setName(e.target.value)} placeholder="media-production"/></label><label className="execution-field"><span>Image reference</span><input className="input-text" required value={reference} onChange={e=>setReference(e.target.value)} placeholder="acme/tools@1.0.0"/></label><label className="execution-field"><span>Export aliases (optional JSON)</span><textarea className="input-textarea" rows={4} value={aliases} onChange={e=>setAliases(e.target.value)} placeholder={'{"resize":"resize-image"}'}/></label><p className="execution-note">Leave aliases blank to use export names. These mappings belong to this immutable generation.</p><label className="execution-field"><span>Worker pin (optional Station ID)</span><input className="input-text" value={stationId} onChange={e=>setStationId(e.target.value)} placeholder="Any eligible worker"/></label><BindingEditor rows={bindings} setRows={setBindings} disabled={busy}/><button className="btn btn-primary" disabled={busy}>{busy?"Staging…":"Stage generation"}</button>
  </form>{error&&<div className="execution-error" role="alert">{error}</div>}</section>;
}
function GenerationDetails({deployment,generation,refresh}:{deployment:Deployment;generation:Generation;refresh:()=>void}) {
  const [action,setAction]=useState<"activate"|"rollback">("activate");const wasActive=deployment.history.some(event=>event.generation===generation.id&&["activate","rollback"].includes(event.action));
  return <><section className="card execution-card registry-panel"><h2>{generation.image.manifest.name} · {generation.image.manifest.version}</h2><p className="registry-digest mono">{generation.image.digest}</p><p className="execution-note">Staged {new Date(generation.createdAt).toLocaleString()} · {generation.stationId?`Pinned to ${generation.stationId}`:"Any eligible worker"}</p><h3>Export aliases</h3>{Object.entries(generation.aliases).map(([alias,exportName])=><div className="registry-dependency" key={alias}><strong>{alias}</strong><span className="mono">{exportName}</span></div>)}<h3>Environment bindings</h3>{Object.entries(generation.bindings??{}).length?Object.entries(generation.bindings??{}).map(([key,binding])=><div className="registry-dependency" key={key}><strong className="mono">{key}</strong><span>{"fromEnv" in binding?`Environment reference: ${binding.fromEnv}`:"Non-secret literal configured"}</span></div>):<p className="execution-note">No generation-specific bindings.</p>}<Link href={`/registry/images/${enc(generation.image.manifest.name)}/versions/${enc(generation.image.manifest.version)}`}>Inspect image version</Link></section>
    {deployment.activeGeneration===generation.id?<p role="status" className="execution-note">This generation is active.</p>:<><div className="execution-toolbar"><button className="btn" onClick={()=>setAction("activate")} aria-pressed={action==="activate"}>Activate</button>{wasActive&&<button className="btn" onClick={()=>setAction("rollback")} aria-pressed={action==="rollback"}>Roll back to this generation</button>}</div><ChangeGeneration key={`${action}-${deployment.revision}`} deployment={deployment} generation={generation} action={action} refresh={refresh}/></>}
  </>;
}
function ChangeGeneration({deployment,generation,action,refresh}:{deployment:Deployment;generation?:Generation;action:"activate"|"rollback"|"drain";refresh:()=>void}) {
  const {post}=useRegistry();
  const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [done,setDone]=useState(false);const label=action==="drain"?"Drain deployment":action==="rollback"?"Roll back generation":"Activate generation";
  return <section className="card execution-card registry-panel"><h2>{label}</h2><p className="execution-note">{action==="drain"?"Remove the active alias pointer so new invocations fail until a generation is activated. Existing runs and beacons continue.":"Future alias invocations use this generation. Existing runs, saved plans and beacon instances keep their original identity."}</p><p className="execution-note">This change requires revision {deployment.revision}. If another operator changes it first, refresh and review again.</p><button className="btn btn-primary" disabled={busy||done||action==="drain"&&!deployment.activeGeneration} onClick={async()=>{setBusy(true);setError(null);try{await post(`/deployments/${enc(deployment.id)}/${action}`,{expectedRevision:deployment.revision,...(generation?{generation:generation.id}:{})});setDone(true);refresh();}catch(e){setError(message(e));}finally{setBusy(false);}}}>{busy?"Applying…":label}</button>{error&&<div className="execution-error" role="alert">{error}</div>}{done&&<p role="status">Deployment updated.</p>}</section>;
}
function RunDeployment({deployment}:{deployment:Deployment}) {
  const {post}=useRegistry();
  const generation=deployment.generations.find(g=>g.id===deployment.activeGeneration);const [alias,setAlias]=useState(generation?Object.keys(generation.aliases)[0]??"":"");const [input,setInput]=useState("{}");const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [result,setResult]=useState<{id:string;kind:string;registeredName:string;generation:string}|null>(null);
  if(!generation)return <p className="execution-note">Activate a generation before invoking this deployment.</p>;
  return <section className="card execution-card registry-panel"><h2>Invoke active alias</h2><p className="execution-note">The daemon pins the active generation when it receives the request. The returned identity records the generation actually used.</p><form onSubmit={async event=>{event.preventDefault();setBusy(true);setError(null);setResult(null);try{setResult(await post(`/deployments/${enc(deployment.id)}/run`,{alias,input:JSON.parse(input)}));}catch(e){setError(message(e));}finally{setBusy(false);}}}><label className="execution-field"><span>Alias</span><select className="input-text" value={alias} onChange={e=>setAlias(e.target.value)}>{Object.keys(generation.aliases).map(key=><option key={key}>{key}</option>)}</select></label><label className="execution-field"><span>Input / configuration JSON</span><textarea className="input-textarea" rows={7} value={input} onChange={e=>setInput(e.target.value)}/></label><button className="btn btn-primary" disabled={busy||!alias}>{busy?"Submitting…":"Invoke alias"}</button></form>{error&&<div className="execution-error" role="alert">{error}</div>}{result&&<div role="status"><p>{result.kind} · <span className="mono">{result.id}</span></p><p className="execution-note">Generation {result.generation}</p><Link className="btn" href={result.kind==="signal"?`/runs/${enc(result.id)}`:result.kind==="broadcast"?`/broadcasts/${enc(result.id)}`:`/beacons/${enc(result.registeredName)}`}>View execution</Link></div>}</section>;
}

interface BindingRow { key:string;kind:"reference"|"literal";value:string;nonsecret:boolean }
function BindingEditor({rows,setRows,disabled}:{rows:BindingRow[];setRows:(rows:BindingRow[])=>void;disabled:boolean}) {
  const update=(index:number,change:Partial<BindingRow>)=>setRows(rows.map((row,i)=>i===index?{...row,...change}:row));
  return <fieldset className="registry-bindings" disabled={disabled}><legend>Environment bindings</legend><p className="execution-note">Reference an environment-store key for credentials. Values resolve on the worker under its environment grants. Literal values are stored in the generation and must not contain secrets.</p>
    {rows.map((row,index)=><div className="registry-binding" key={index}>
      <label className="execution-field"><span>Binding {index+1} key</span><input className="input-text" required value={row.key} onChange={event=>update(index,{key:event.target.value})} placeholder="API_TOKEN"/></label>
      <label className="execution-field"><span>Binding {index+1} source</span><select className="input-text" aria-label={`Binding ${index+1} source`} value={row.kind} onChange={event=>update(index,{kind:event.target.value as BindingRow["kind"],value:"",nonsecret:false})}><option value="reference">Environment reference</option><option value="literal">Non-secret literal</option></select></label>
      <label className="execution-field"><span>{row.kind==="reference"?`Binding ${index+1} environment key`:`Binding ${index+1} non-secret value`}</span><input className="input-text" autoComplete="off" required={row.kind==="reference"} value={row.value} onChange={event=>update(index,{value:event.target.value})} placeholder={row.kind==="reference"?"SHARED_API_TOKEN":"production"}/></label>
      {row.kind==="literal"&&<label><input type="checkbox" required checked={row.nonsecret} onChange={event=>update(index,{nonsecret:event.target.checked})}/> I confirm binding {index+1} contains no secret</label>}
      <button type="button" className="btn" onClick={()=>setRows(rows.filter((_,i)=>i!==index))}>Remove binding {index+1}</button>
    </div>)}
    <button type="button" className="btn" onClick={()=>setRows([...rows,{key:"",kind:"reference",value:"",nonsecret:false}])}>Add environment binding</button>
  </fieldset>;
}
